OpenCyphal/pydsdl

- pydsdl/dsdl_parser.py
Problem:
There's not enough information in the InvalidFixedPortIDError to
diagnose the real error.
Solution:
Include if the ID was for a service or message type and include the full
path. This allows the user to see which ID range they violated or if
this is just a path error.
Testing:
Fed invalid identifiers and verified that the message is more
informative.
> Adding better error messaging for port ID check

- .travis.yml
- pydsdl/__init__.py
Python 3.5.2 turned out to be unsupported because there was an issue in the static typing library: https://github.com/python/typing/pull/308. The issue has been fixed in Python 3.5.3, so all newer versions function correctly. This is how you can reproduce the problem:
```python
>>> import typing
>>> T = typing.TypeVar('T')
>>> G = typing.Callable[[], T]
>>> G[int]
typing.Callable[[], int]
```
The above is the expected behavior observable in Python 3.5.3+. In 3.5.2 you get this instead:
```text
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.5/typing.py", line 815, in __getitem__
raise TypeError("This Callable type is already parameterized.")
TypeError: This Callable type is already parameterized.
```
An alternative solution would be to remove …
> Python compatibility clarifications

- pydsdl/__init__.py
- pydsdl/_bit_length_set.py
- pydsdl/_serializable/_array.py
- pydsdl/_serializable/_composite.py
- pydsdl/_test.py
See https://github.com/UAVCAN/specification/issues/75
> Implement implicit field size alignment

- README.md
- pydsdl/__init__.py
- pydsdl/_bit_length_set.py
- pydsdl/_data_type_builder.py
- pydsdl/_serializable/__init__.py
- pydsdl/_serializable/_attribute.py
- pydsdl/_serializable/_composite.py
- pydsdl/_test.py
TaggedUnionType removed, other changes left intact.
The reversal is done semi-manually by copying files from v1.2 and by reverting _test.py back to the pre-#34 state via git diff <range>; git apply.
See Slack for details.
> Partial reversal of #34

- .idea/dictionaries/pavel.xml
- pydsdl/_data_type_builder.py
- pydsdl/_dsdl_definition.py
- pydsdl/_namespace.py
- pydsdl/_test.py
Fixes #41
Fixes #42
Now, in case of an accidental misuse like in https://forum.uavcan.org/t/dsdl-compilation-error/904/2, the error message will contain a helpful suggestion:
```
/home/pavel/test/demo/dsdl/my_namespace/Trajectory.1.0.uavcan:1: Data type my_namespace.PointXY.1.0 could not be found in the following root namespaces: {'dsdl'}.  Did you mean to use the directory '/home/pavel/test/demo/dsdl/my_namespace' instead of '/home/pavel/test/demo/dsdl'?
```
> Fix #41 and #42

- pydsdl/__init__.py
- pydsdl/_bit_length_set.py
- pydsdl/_serializable/_array.py
Fix #49
Performance profiling script:
```python
#!/usr/bin/env python
import sys
import pathlib
import cProfile
sys.path.append(str(pathlib.Path(__file__).parent))
import pydsdl
cProfile.run('''pydsdl.read_namespace('.dsdl-test/uavcan', [])''', sort=1)
```
This PR brings the execution time of the above script from 63 seconds down to 3 seconds. It is possible to do better but it wouldn't be trivial. Maybe we need dsdl.rs?
Alternative profiling script that also parses the `reg` namespace:
```python
#!/usr/bin/env python
import sys
import pathlib
import cProfile
sys.path.append(str(pathlib.Path(__file__).parent))
import pydsdl
cProfile.run('''
pydsdl.read_namespace('.dsdl-test/reg', ['.dsdl-test/uavcan'])
pydsdl.read_namespace('.dsdl-test/uavcan', [])
''', sort=1)
```
> Performance improvements; fix #49

- pydsdl/__init__.py
- pydsdl/_data_schema_builder.py
- pydsdl/_data_type_builder.py
- pydsdl/_namespace.py
- pydsdl/_serializable/_composite.py
- pydsdl/_test.py
If neither extent nor sealing is specified, we report an error (per https://github.com/UAVCAN/specification/pull/102). The error hints the user that maybe `@extent` is the way to go, with the suggested value computed as follows:
https://github.com/UAVCAN/pydsdl/blob/8a6d9b5fb0be8ca9ddcb37e60fc2349b35903fab/pydsdl/_data_type_builder.py#L320-L325
Since this is an implementation-specific behavior, we can change it on a whim at any moment if found suboptimal.
@thirtytwobits please confirm the logic. There is no need to look at the code.
> Make `@sealed` or `@extent ...` required. Provide usage hints when neither are found.

- pydsdl/__init__.py
- pydsdl/_data_type_builder.py
- pydsdl/_expression/_any.py
- pydsdl/_serializable/_composite.py
- pydsdl/_test.py
This is a minor change in the internals. Not visible from the outside other than it makes `pydsdl.Any` picklable again.
> Make pydsdl.Any picklable

- pydsdl/__init__.py
- pydsdl/_serializable/_composite.py
Currently, inner_type is defined only for DelimitedType. This changeset makes it a CompositeType property that returns a reference to self unless self is DelimitedType.
> Add a convenience property CompositeType.inner_type to reduce boilerplate

- pydsdl/__init__.py
- pydsdl/_serializable/_composite.py
This allows code generators to avoid emitting unnecessary saturation code. Also, the type is now constructed only once to stay consistent with unions and variable-length arrays.
> Make DelimitedType.delimiter_header_type truncated (not saturated)

- pydsdl/__init__.py
- pydsdl/_namespace.py
- pydsdl/_test.py
Fix #60
@PetervdPerk-NXP can you please verify this? This is how you can deploy this version locally for testing:
```
pip install git+https://github.com/UAVCAN/pydsdl@issue-60
```
> Fix duplicate path detection

- pydsdl/__init__.py
- pydsdl/_parser.py
Fix #29
Also, remove unnecessary dev scaffolding.
Before:
import time:       658 |     216301 | pydsdl
After:
import time:      3118 |      90038 | pydsdl
216 ms -> 90 ms
This is important for command-line tools like Nunavut and Yakut
> Speed up import

- pydsdl/__init__.py
- pydsdl/_data_schema_builder.py
- pydsdl/_data_type_builder.py
- pydsdl/_parser.py
- pydsdl/_serializable/_attribute.py
- pydsdl/_serializable/_composite.py
- pydsdl/_test.py
This PR adds documentation support for #21. It exposes
comments on attributes and composite types (following proto convention
of having the comment come after the attribute) on a `doc: str` property
as described in https://forum.uavcan.org/t/generate-rich-navigable-html-docs-using-nunavut/1163.
> Add doc attributes to composite and attribute types

- appveyor.yml
- docs/_static/custom.css
- docs/requirements.txt
- noxfile.py
- pydsdl/third_party/six.py
Improves compatibility with Python 3.10
@thirtytwobits Could you share your local environment setup so I can test it correctly? Nevertheless, this updates the bundled six which should theoretically solve the problem.
I'm also working on migrating pyuavcan to support numpy >= 1.20, which allows 3.10 support.
> third_party: update six to 1.16

- .idea/dictionaries/pavel.xml
- appveyor.yml
- noxfile.py
- pydsdl/__init__.py
- pydsdl/_data_schema_builder.py
- pydsdl/_data_type_builder.py
- pydsdl/_dsdl_definition.py
- pydsdl/_error.py
- pydsdl/_namespace.py
- pydsdl/_parser.py
- pydsdl/_serializable/_composite.py
- pydsdl/_serializable/_name.py
- pydsdl/_serializable/_primitive.py
- pydsdl/_test.py
- setup.cfg
This is not expected to break the API. Uniform path representation can be obtained using `.as_posix()`:
This changeset also updates the test dependencies and drops Python 3.6 from the CI rig.
Fixes #76 
Relates to https://github.com/UAVCAN/nunavut/pull/239 and https://github.com/UAVCAN/nunavut/pull/195
> Use pathlib.Path instead of plain string paths

- .devcontainer/devcontainer.json
- .github/workflows/test-and-release.yml
- .gitmodules
- .readthedocs.yml
- conftest.py
- docs/pages/pydsdl.rst
- docs/requirements.txt
- noxfile.py
- pydsdl/__init__.py
- pydsdl/_bit_length_set/_symbolic_test.py
- pydsdl/_data_type_builder.py
- pydsdl/_dsdl.py
- pydsdl/_dsdl_definition.py
- pydsdl/_error.py
- pydsdl/_namespace.py
- pydsdl/_namespace_reader.py
- pydsdl/_parser.py
- pydsdl/_serializable/_composite.py
- pydsdl/_test.py
- setup.cfg
- test/test_public_types.py
This is non-breaking change that adds a new public method:
read_files - a file-oriented entry point to the front end. This takes a list of target DSDL files allowing the user to maintain an explicit list instead of depending on globular filesystem discovery. Furthermore this method returns a set which is the transitive closure of types depended on by the target list of types. This allows consumers to track dependencies and compiler back ends to generate .d files and otherwise support incremental builds.
The new method may increase performance for systems with large pools of messages when generating code for a small sub-set as it only considers the target and dependencies of the target when parsing dsdl files.
> Adding support for file-based reads and externalized type dependencies

- pydsdl/__init__.py
- pydsdl/_data_type_builder.py
- pydsdl/_namespace.py
- pydsdl/_test.py
This changes our logic for detecting duplicate definitions on case-sensitive file-systems to only operate on files of interest and to fix this detection logic per issue #104.
If globular searches find duplicates we do not waste time detecting this until/unless these duplicates are actually considered when parsing target definitions.
> Fix for Issue #104

- pydsdl/__init__.py
- pydsdl/_dsdl.py
- pydsdl/_dsdl_definition.py
- pydsdl/_namespace.py
- pydsdl/_namespace_reader.py
Fix for issue #109. This relaxes some logic that required existing paths before creating a DSDLFile abstraction while adding a requirement that ReadableDSDLFile(s) are created with files that exist (i.e. it can't be "readable" if it doesn't exist). At the same time, we clarified (and fixed) the difference between the `root_namespace_directories_or_names` and `lookup_directories arguments` of read_files. Our new guidance is to dis-use `lookup_directories` unless there is a need to separate target lookup paths from dependent type look up paths. This was an unstated design goal that I forgot about and subsequently mis-implemented. This does change the behaviour of the API slightly which is why I've bumped the minor version instead of just the patch.
> Allow relative target paths

- pydsdl/__init__.py
- pydsdl/_data_schema_builder.py
- pydsdl/_dsdl_definition.py
Resolve inputs into DSDLDefinition constructor
> Fix for issue #111

- pydsdl/__init__.py
- pydsdl/_dsdl_definition.py
This is causing Nunavut 3.0 to become unresponsive if given a bad path.
> Fix for #114
